spring.application.name=solicitacoes-internas

spring.datasource.url=jdbc:postgresql://localhost:5432/portal_solicitacoes
spring.datasource.username=postgres
spring.datasource.password=fla140499

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

api.security.token.secret=uma-chave-secreta-muito-grande-para-o-jwt-do-projeto

